### ISSUE TITLE
Кривое отображение тени в кнопке "отравить"

### ISSUE THREAD

**Issue by compico** [Yoshikomaru195/feedback-counter_v2#3]
https://github.com/Yoshikomaru195/feedback-counter_v2/blob/37cdc66869ba92acfc363626d666f74ccf241898/sass/style.sass#L18

![изображение](https://user-images.githubusercontent.com/2575585/79415410-06052f80-7fb6-11ea-8ad9-4672fe021ef6.png)

Пиши свою фронту.
Firefox.

**Comment by compico** [comment]
Проблема только на Firefox'е. Мб даже и не нужно решать.

На хроме это выглядит так:
![изображение](https://user-images.githubusercontent.com/2575585/79415798-ede1e000-7fb6-11ea-85e1-1b4417cfdec9.png)

**Comment by Yoshikomaru195** [comment]
Поправим
